In [12]:
import pandas as pd
import numpy as np
import copy

|Data Type| Mutable/Immutable|
|------|------|
|bool  | Immutable|
|int  | Immutable|
|float  | Immutable|
|   list  | Mutable|
|   tuple  | Immutable|
|   str  | Immutable|
|   set  | Mutable|
|   frozen set  | Immutable|
|   dict  | Mutable|
|   User Defined Class  | Mutable|

In [26]:
x = 1000
z = 1000
print(hex(id(x)), hex(id(z)))
print(x is z)
y = x
x = x + 1
print(x, y)
print(x is y)
y = copy.deepcopy(x)
print(hex(id(x)), hex(id(y)))
print(x is y)
# print(hex(id(x)), hex(id(y)))

0x7faf3aefa830 0x7faf3aefa890
False
1001 1000
False
0x7faf3aefafb0 0x7faf3aefafb0
True


In [29]:
class Human:
    def __init__(self, height, eyeColor):
        self.height = height
        self.eyeColor = eyeColor
    
    def getEyeColor(self):
#         print(hex(id(self.eyeColor)))
        return self.eyeColor
    
    def getHeight(self):
#         print(hex(id(self.height)))
        return self.height

In [66]:
amit = Human(165, "black")
print(amit.getHeight(), amit.getEyeColor())

165 black


In [71]:
abc = amit
print("abc is amit: ", abc is amit)
print("amit is name of address: ", hex(id(amit)), "abc is name of address:", hex(id(abc)))
abc = copy.copy(amit)
print("---------------------")
print("abc is amit: ", abc is amit)
print("amit is name of address: ", hex(id(amit)), "abc is name of address:", hex(id(abc)))

abc is amit:  True
amit is name of address:  0x7faf3ab4dba8 abc is name of address: 0x7faf3ab4dba8
---------------------
abc is amit:  False
amit is name of address:  0x7faf3ab4dba8 abc is name of address: 0x7faf3ae81a20


** Integer **
- Integer belongs to class int
- Integer is immutable
- an immutable object can not be changed

In [78]:
x = 1000         #1000 is object and x is name of that object
print("Type of x: ", type(x))     #int is a class

y = x            #assign reference; like x and y are different names of same person
print("y is name of address: ", hex(id(y)), "x is name of address: ", hex(id(x)))
print("---------------------")
y = 1000         #1000 is a new object and y is name of new object
print("y is name of address: ", hex(id(y)), "x is name of address: ", hex(id(x)))
print("---------------------")
y = x + 1       #since x is immutable and hence can not be changed, therefore a new object with value x + 1..
                #is created and y is name of that new object; x is still name of old object
print("x: ",y,"y: ", x)
print("y is name of address: ", hex(id(y)), "x is name of address: ", hex(id(x)))

Type of x:  <class 'int'>
y is name of address:  0x7faf3ab3a250 x is name of address:  0x7faf3ab3a250
---------------------
y is name of address:  0x7faf3ab3a230 x is name of address:  0x7faf3ab3a250
---------------------
x:  1001 y:  1000
y is name of address:  0x7faf3aefa670 x is name of address:  0x7faf3ab3a250


In [95]:
amit = Human(165, "black")
abc = copy.copy(amit)
# abc = amit
print(hex(id(amit)), hex(id(abc)))
print(hex(id(amit.getHeight())), hex(id(amit.getEyeColor())))
print(hex(id(abc.getHeight())), hex(id(abc.getEyeColor())))
abc.height = 155
print(abc.getHeight(), amit.getHeight())
print(hex(id(amit.getHeight())), hex(id(amit.getEyeColor())))
print(hex(id(abc.getHeight())), hex(id(abc.getEyeColor())))

0x7faf3ab5f828 0x7faf3ab5fb70
0x7faf72e530a0 0x7faf6b555e68
0x7faf72e530a0 0x7faf6b555e68
155 165
0x7faf72e530a0 0x7faf6b555e68
0x7faf72e52f60 0x7faf6b555e68


In [103]:
class Tiger:
    def __init__ (self, height, charList):
        self.height = height
        self.charList = charList
        
t1 = Tiger(134, [1, 2, 3])
t2 = copy.copy(t1)
print(t1.charList, t2.charList)
t2.charList[1] = 10
print(t1.charList, t2.charList)
print(hex(id(t1.height)), hex(id(t1.charList)))
print(hex(id(t2.height)), hex(id(t2.charList)))
print([hex(id(x)) for x in t1.charList])
print([hex(id(x)) for x in t2.charList])

[1, 2, 3] [1, 2, 3]
[1, 10, 3] [1, 10, 3]
0x7faf72e52cc0 0x7faf3ab06048
0x7faf72e52cc0 0x7faf3ab06048
['0x7faf72e51c20', '0x7faf72e51d40', '0x7faf72e51c60']
['0x7faf72e51c20', '0x7faf72e51d40', '0x7faf72e51c60']


In [109]:
t1 = Tiger(134, [1, 2, 3])
t2 = copy.deepcopy(t1)
print(t1.charList, t2.charList)
t2.charList[1] = 101
print(t1.charList, t2.charList)
print(hex(id(t1.height)), hex(id(t1.charList)))
print(hex(id(t2.height)), hex(id(t2.charList)))
print([hex(id(x)) for x in t1.charList])
print([hex(id(x)) for x in t2.charList])

[1, 2, 3] [1, 2, 3]
[1, 2, 3] [1, 101, 3]
0x7faf72e52cc0 0x7faf3aa7cc08
0x7faf72e52cc0 0x7faf3aa7c848
['0x7faf72e51c20', '0x7faf72e51c40', '0x7faf72e51c60']
['0x7faf72e51c20', '0x7faf72e528a0', '0x7faf72e51c60']


In [75]:
allVar = dict({})

In [76]:
insertVar('amit', hex(id(amit)))
insertVar('abc', hex(id(abc)))
insertVar('vikram', hex(id(vikram)))
makeEqual()
print(allVar)
display(pd.DataFrame(allVar, index = ["Name1", "Name2"]))

{'0x7f08185f6748': ['amit', 'abc'], '0x7f07ee12b940': ['vikram', ' ']}


0x7f07ee12b940 0x7f08185f6748
Name1         vikram           amit
Name2                           abc

In [73]:
def makeEqual():
    maxLen = 0;
    for key in allVar:
        if(len(allVar[key]) > maxLen):
            maxLen = len(allVar[key])
                     
    for key in allVar:
        allVar[key].extend([' ']*(maxLen - len(allVar[key])))
                

In [74]:
def insertVar(nameVar, Id):
    if Id in allVar:
        allVar[Id].append(nameVar)
    else:
        allVar[Id] = [nameVar]

In [79]:
i = 10
j = i
j+=1
print(hex(id(i)), hex(id(j)))
print(i, j)

0x7f082621cd40 0x7f082621cd60
10 11


In [89]:
arr = np.array([1, 2, 3])
arr1 = arr
print("arr: ",arr, "\narr1:", arr1)
print("arr Refers to: ",hex(id(arr)), "\narr1 referes to: ", hex(id(arr1)))
arr1[2] = 10
print("-----------------------")
print("arr: ",arr, "\narr1:", arr1)
print("arr Refers to: ",hex(id(arr)), "\narr1 referes to: ", hex(id(arr1)))
print("-------------------------")
arr1 = np.array([3, 4, 5])
print("arr: ",arr, "\narr1:", arr1)
print("arr Refers to: ",hex(id(arr)), "\narr1 referes to: ", hex(id(arr1)))
print("-------------------------")
arr1 = arr[:3]
di("arr: ",arr, "\narr1:", arr1)
print("arr Refers to: ",hex(id(arr)), "\narr1 referes to: ", hex(id(arr1)))

arr:  [1 2 3] 
arr1: [1 2 3]
arr Refers to:  0x7f07ede1b8f0 
arr1 referes to:  0x7f07ede1b8f0
-----------------------
arr:  [ 1  2 10] 
arr1: [ 1  2 10]
arr Refers to:  0x7f07ede1b8f0 
arr1 referes to:  0x7f07ede1b8f0
-------------------------
arr:  [ 1  2 10] 
arr1: [3 4 5]
arr Refers to:  0x7f07ede1b8f0 
arr1 referes to:  0x7f07ede0d8f0
-------------------------
arr:  [ 1  2 10] 
arr1: [ 1  2 10]
arr Refers to:  0x7f07ede1b8f0 
arr1 referes to:  0x7f07ede14df0


In [47]:
a = [10, 2, 3]
b = copy.deepcopy(a)
print(a, b)
b[0] = 10
print(a, b)
print(hex(id(a)), hex(id(b)))
print([hex(id(x)) for x in a])
print([hex(id(x)) for x in b])

[10, 2, 3] [10, 2, 3]
[10, 2, 3] [101, 2, 3]
0x7faf3aba6f88 0x7faf3ab9ec48
['0x7faf72e51d40', '0x7faf72e51c40', '0x7faf72e51c60']
['0x7faf72e528a0', '0x7faf72e51c40', '0x7faf72e51c60']


In [48]:
c = 10
print(hex(id(c)))

0x7faf72e51d40


In [94]:
a = [1,2,3,[4,5],6]
b = a
print(a, b)
print("a: ",hex(id(a)), "b: ", hex(id(b)))
print([hex(id(x)) for x in a])
print([hex(id(x)) for x in b])
print("---------------------")
b = a[:]    #equivalent = a.copy() or copy.copy(a) or list(a)  = swallow copy
b[0] = 123
b[3]= [1, 2]
print(a, b)
print("a: ",hex(id(a)), "b: ", hex(id(b)))
print([hex(id(x)) for x in a])
print([hex(id(x)) for x in b])
print("---------------------")
b = copy.deepcopy(a)
b[0] = 121
b[3][0] = 13
print(b, a)
print("a: ",hex(id(a)), "b: ", hex(id(b)))
print([hex(id(x)) for x in a])
print([hex(id(x)) for x in b])
print("---------------------")
print([hex(id(x)) for x in a[3]])
print([hex(id(x)) for x in b[3]])

[1, 2, 3, [4, 5], 6] [1, 2, 3, [4, 5], 6]
a:  0x7faf3ab060c8 b:  0x7faf3ab060c8
['0x7faf72e51c20', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab12dc8', '0x7faf72e51cc0']
['0x7faf72e51c20', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab12dc8', '0x7faf72e51cc0']
---------------------
[1, 2, 3, [4, 5], 6] [123, 2, 3, [1, 2], 6]
a:  0x7faf3ab060c8 b:  0x7faf3ab5bec8
['0x7faf72e51c20', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab12dc8', '0x7faf72e51cc0']
['0x7faf72e52b60', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab5b5c8', '0x7faf72e51cc0']
---------------------
[121, 2, 3, [13, 5], 6] [1, 2, 3, [4, 5], 6]
a:  0x7faf3ab060c8 b:  0x7faf3ab1af48
['0x7faf72e51c20', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab12dc8', '0x7faf72e51cc0']
['0x7faf72e52b20', '0x7faf72e51c40', '0x7faf72e51c60', '0x7faf3ab061c8', '0x7faf72e51cc0']
---------------------
['0x7faf72e51c80', '0x7faf72e51ca0']
['0x7faf72e51da0', '0x7faf72e51ca0']


In [114]:
l1 = [1, 2, 3, 4, 5]
l2 = l1[:3]     #swallow copy   
l2[0] = 10
print(l1)
print(l2)
l3 = l1
l3[0] = 101
print(l1)
print(l3)

[1, 2, 3, 4, 5]
[10, 2, 3]
[101, 2, 3, 4, 5]
[101, 2, 3, 4, 5]


In [128]:
arr1 = np.array([[1,2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = copy.copy(arr1)
print(arr1)
print(arr2)
arr2[0][0] = 101
# arr2[0] = np.array([101,102, 103])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [63]:
def update(ia):
    print(hex(id(ia)))
x = 1000
print("x: ", hex(id(x)))
update(x)
print("x: ", hex(id(x)))

x:  0x7faf3ab3a090
0x7faf3ab3a090
x:  0x7faf3ab3a090
