In [29]:
import numpy as np

### Array information

In [30]:
arr = np.array([[1,2,1],[3,0,9]])
arr1= np.array([[[1,2,1],[4,5,3],[7,8,9]]])
print(arr1.shape,arr1.ndim)
print(arr.shape,arr.ndim)

(1, 3, 3) 3
(2, 3) 2


In [31]:
print(arr.size)   #total number of elements in array
print(arr1.size)

print(arr.dtype)  #data type 
print(arr1.dtype)

6
9
int64
int64


### Array Creation

In [32]:
arr2 = np.array([[1,2,1],[3, 8, 9]], dtype = complex)
print(arr2)

[[ 1.+0.j  2.+0.j  1.+0.j]
 [ 3.+0.j  8.+0.j  9.+0.j]]


In [33]:
arr3 = np.zeros((3,2))
print(arr3)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [34]:
arr4 = np.ones((2,3))
print(arr4)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [38]:
arr9 = np.empty( (2,3) )
print(arr9)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [37]:
arr6 = np.empty_like(arr)
print(arr6)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [46]:
arr7 = np.arange(10,30,5)  #numbers in the range [10, 30) starting from 10 and taking step of 5
print(arr7)
print(np.arange(5))

[10 15 20 25]
[0 1 2 3 4]


In [75]:
arr8 = np.linspace(0,2,9)  #9 numbers between 0 and 2 including 0 and 2
print(arr8)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


In [76]:
np.random.random((2,3))

array([[ 0.96160727,  0.75863958,  0.17266719],
       [ 0.66264585,  0.50791611,  0.15014924]])

In [77]:
np.random.rand(2,3)

array([[ 0.28006912,  0.32430061,  0.35548845],
       [ 0.83390146,  0.06236048,  0.37901475]])

In [78]:
np.random.randn(2,3)   #normally distributed numbers between 0 and 1 of shape (2,3)

array([[-0.0689275 ,  2.22939021, -0.17331526],
       [-0.33166257,  0.49597337,  0.44366826]])

In [79]:
np.random.randint(2,20,5)    #5 random integers between 2 and 20 

array([ 3, 19, 17, 10,  9])

### Basic Operations

In [53]:
print(arr)

[[1 2 1]
 [3 0 9]]


In [52]:
b = arr*2
b

array([[ 2,  4,  2],
       [ 6,  0, 18]])

In [49]:
arr**2

array([[ 1,  4,  1],
       [ 9,  0, 81]])

In [55]:
b - arr

array([[1, 2, 1],
       [3, 0, 9]])

In [57]:
b*arr

array([[  2,   8,   2],
       [ 18,   0, 162]])

In [59]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.84147098],
       [ 0.14112001,  0.        ,  0.41211849]])

In [60]:
arr<3

array([[ True,  True,  True],
       [False,  True, False]], dtype=bool)

In [63]:
arr[arr<3] = 100
print(arr)

[[100 100 100]
 [  3 100   9]]


In [118]:
print(b)
print(b.sum())
print(b.sum(axis = 0))
print(b.sum(axis =1 ))

[[ 2  4  2]
 [ 6  0 18]]
32
[ 8  4 20]
[ 8 24]


In [88]:
print(b.cumsum(axis = 0))

[[ 2  4  2]
 [ 8  4 20]]


### Universal Functions

In [89]:
print(arr)

[[100 100 100]
 [  3 100   9]]


In [90]:
print(np.sqrt(arr))

[[ 10.          10.          10.        ]
 [  1.73205081  10.           3.        ]]


In [91]:
print(np.exp(arr))

[[  2.68811714e+43   2.68811714e+43   2.68811714e+43]
 [  2.00855369e+01   2.68811714e+43   8.10308393e+03]]


In [110]:
np.add(arr, b)

array([[102, 104, 102],
       [  9, 100,  27]])

In [111]:
np.any(arr)

True

In [112]:
print(arr3)
print(np.any(arr3))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
False


In [113]:
np.all(arr)

True

In [114]:
arr3[0,1]=1
arr3

array([[ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [119]:
print(np.all(arr3))
print(np.any(arr3))

False
True


In [121]:
print(b)
print(b.min())
print(b.argmin())
print(b.min(axis = 0))
print(b.argmin(axis = 0))

[[ 2  4  2]
 [ 6  0 18]]
0
4
[2 0 2]
[0 1 0]


### Indexing, Slicing and Iterating

In [102]:
print(arr)

[[100 100 100]
 [  3 100   9]]


In [104]:
arr[0:2,0:1]

array([[100],
       [  3]])

In [105]:
arr[0:2,0:2]

array([[100, 100],
       [  3, 100]])

In [106]:
arr[0:2,0:3:2]

array([[100, 100],
       [  3,   9]])

In [107]:
arr[:,:]

array([[100, 100, 100],
       [  3, 100,   9]])

In [108]:
arr[:-1,:]

array([[100, 100, 100]])

In [109]:
arr[:-1,:-1]

array([[100, 100]])

### Shape Manipulation

In [124]:
print(arr)
print(arr.shape)
arr = arr.reshape(2,3)
print(arr)

[[100 100]
 [100   3]
 [100   9]]
(3, 2)
[[100 100 100]
 [  3 100   9]]


In [125]:
arr.ravel()

array([100, 100, 100,   3, 100,   9])

In [127]:
arr.flat

In [129]:
list(arr.flat)

[100, 100, 100, 3, 100, 9]

In [131]:
np.array(arr.flat)

array([100, 100, 100,   3, 100,   9])

In [132]:
print(arr1)

[[[1 2 1]
  [4 5 3]
  [7 8 9]]]


In [135]:
arr1.ravel()

array([1, 2, 1, 4, 5, 3, 7, 8, 9])

In [134]:
list(arr1.flat)

[1, 2, 1, 4, 5, 3, 7, 8, 9]

In [136]:
np.array(arr1.flat)

array([1, 2, 1, 4, 5, 3, 7, 8, 9])

### Stacking Together

In [137]:
print(arr)
print(b)

[[100 100 100]
 [  3 100   9]]
[[ 2  4  2]
 [ 6  0 18]]


In [139]:
np.vstack((arr,b))

array([[100, 100, 100],
       [  3, 100,   9],
       [  2,   4,   2],
       [  6,   0,  18]])

In [140]:
np.hstack((arr,b))

array([[100, 100, 100,   2,   4,   2],
       [  3, 100,   9,   6,   0,  18]])

In [143]:
col = np.arange(2)
col

array([0, 1])

In [144]:
np.column_stack((arr, col))

array([[100, 100, 100,   0],
       [  3, 100,   9,   1]])

In [156]:
np.hstack((arr, col.reshape(2,1)))

array([[100, 100, 100,   0],
       [  3, 100,   9,   1]])

In [157]:
np.tile(arr,(3,1))

array([[100, 100, 100],
       [  3, 100,   9],
       [100, 100, 100],
       [  3, 100,   9],
       [100, 100, 100],
       [  3, 100,   9]])

In [158]:
np.tile(arr,(3,2))

array([[100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9],
       [100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9],
       [100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9]])

### Splitting Array

In [153]:
print(arr)
np.hsplit(arr,3)

[[100 100 100]
 [  3 100   9]]


[array([[100],
        [  3]]), array([[100],
        [100]]), array([[100],
        [  9]])]

In [155]:
np.vsplit(arr,2)

[array([[100, 100, 100]]), array([[  3, 100,   9]])]

### Copies and views

In [162]:
c = arr
c is arr

True

In [163]:
arr

array([[100, 100, 100],
       [  3, 100,   9]])

In [165]:
d = arr[:1,:]
d

array([[100, 100, 100]])

In [166]:
d is arr

False

In [168]:
d.base is arr

False

In [170]:
d[0,0] = 112
print(d)
print(arr)

[[112 100 100]]
[[112 100 100]
 [  3 100   9]]


In [172]:
# Function calls make no copy
def func(x):
    print(id(x))
func(arr)
print(id(arr))

139930304419120
139930304419120


In [176]:
def func1(x):
    print("x= ",x)
    print("xId= ",id(x))
    x[0,0]= 197
    temp = np.ones((3,2))
    print("tempId= ",id(temp))
    x = temp
    x[0,0]=36
    print("x= ",x)
    print("xId= ",id(x))

print(arr)
print(id(arr))
func1(arr)
print(arr)
print(id(arr))

[[112 100 100]
 [  3 100   9]]
139930304419120
x=  [[112 100 100]
 [  3 100   9]]
xId=  139930304419120
tempId=  139930304547696
x=  [[ 36.   1.]
 [  1.   1.]
 [  1.   1.]]
xId=  139930304547696
[[197 100 100]
 [  3 100   9]]
139930304419120


### Indexing more    

In [177]:
print(arr)

[[197 100 100]
 [  3 100   9]]


In [181]:
ind = np.array([0,])
arr[ind, 0:3]

array([[197, 100, 100],
       [  3, 100,   9]])