In [1]:
import numpy as np

### Array information

In [3]:
arr = np.array([[1, 2, 3], [3, 0, 9]])
print(arr.shape)

(2, 3)


In [193]:
arr = np.array([[1,2,1],[3,0,9]])
arr1= np.array([[[1,2,1],[4,5,3],[7,8,9]]])
print(arr1.shape,arr1.ndim)
print(arr.shape,arr.ndim)

(1, 3, 3) 3
(2, 3) 2


In [194]:
print(arr.size)   #total number of elements in array
print(arr1.size)

print(arr.dtype)  #data type 
print(arr1.dtype)

6
9
int64
int64


### Array Creation

In [195]:
arr2 = np.array([[1,2,1],[3, 8, 9]], dtype = complex)
print(arr2)

[[ 1.+0.j  2.+0.j  1.+0.j]
 [ 3.+0.j  8.+0.j  9.+0.j]]


In [196]:
arr3 = np.zeros((3,2))
print(arr3)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [197]:
arr4 = np.ones((2,3))
print(arr4)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [198]:
arr9 = np.empty( (2,3) )
print(arr9)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [199]:
arr6 = np.empty_like(arr)
print(arr6)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [200]:
arr7 = np.arange(10,30,5)  #numbers in the range [10, 30) starting from 10 and taking step of 5
print(arr7)
print(np.arange(5))

[10 15 20 25]
[0 1 2 3 4]


In [201]:
arr8 = np.linspace(0,2,9)  #9 numbers between 0 and 2 including 0 and 2
print(arr8)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


In [202]:
np.random.random((2,3))

array([[ 0.00835936,  0.14271696,  0.21303764],
       [ 0.38310487,  0.65989892,  0.47367841]])

In [203]:
np.random.rand(2,3)

array([[ 0.19565501,  0.27205304,  0.16194183],
       [ 0.21263169,  0.2623272 ,  0.63856276]])

In [204]:
np.random.randn(2,3)   #normally distributed numbers between 0 and 1 of shape (2,3)

array([[ 0.06377549, -0.41613543,  1.00815776],
       [-0.77436364,  0.33162958, -0.30134831]])

In [205]:
np.random.randint(2,20,5)    #5 random integers between 2 and 20 

array([ 5, 12,  8,  5, 14])

### Basic Operations

In [206]:
print(arr)

[[1 2 1]
 [3 0 9]]


In [207]:
b = arr*2
b

array([[ 2,  4,  2],
       [ 6,  0, 18]])

In [208]:
arr**2

array([[ 1,  4,  1],
       [ 9,  0, 81]])

In [209]:
b - arr

array([[1, 2, 1],
       [3, 0, 9]])

In [210]:
b*arr

array([[  2,   8,   2],
       [ 18,   0, 162]])

In [211]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.84147098],
       [ 0.14112001,  0.        ,  0.41211849]])

In [212]:
arr<3

array([[ True,  True,  True],
       [False,  True, False]], dtype=bool)

In [213]:
arr[arr<3] = 100
print(arr)

[[100 100 100]
 [  3 100   9]]


In [214]:
print(b)
print(b.sum())
print(b.sum(axis = 0))
print(b.sum(axis =1 ))

[[ 2  4  2]
 [ 6  0 18]]
32
[ 8  4 20]
[ 8 24]


In [215]:
print(b.cumsum(axis = 0))

[[ 2  4  2]
 [ 8  4 20]]


### Universal Functions

In [216]:
print(arr)

[[100 100 100]
 [  3 100   9]]


In [217]:
print(np.sqrt(arr))

[[ 10.          10.          10.        ]
 [  1.73205081  10.           3.        ]]


In [218]:
print(np.exp(arr))

[[  2.68811714e+43   2.68811714e+43   2.68811714e+43]
 [  2.00855369e+01   2.68811714e+43   8.10308393e+03]]


In [219]:
np.add(arr, b)

array([[102, 104, 102],
       [  9, 100,  27]])

In [220]:
np.any(arr)

True

In [221]:
print(arr3)
print(np.any(arr3))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
False


In [222]:
np.all(arr)

True

In [223]:
arr3[0,1]=1
arr3

array([[ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [224]:
print(np.all(arr3))
print(np.any(arr3))

False
True


In [225]:
print(b)
print(b.min())
print(b.argmin())
print(b.min(axis = 0))
print(b.argmin(axis = 0))

[[ 2  4  2]
 [ 6  0 18]]
0
4
[2 0 2]
[0 1 0]


### Indexing, Slicing and Iterating

In [226]:
print(arr)

[[100 100 100]
 [  3 100   9]]


In [227]:
arr[0:2,0:1]

array([[100],
       [  3]])

In [228]:
arr[0:2,0:2]

array([[100, 100],
       [  3, 100]])

In [229]:
arr[0:2,0:3:2]

array([[100, 100],
       [  3,   9]])

In [230]:
arr[:,:]

array([[100, 100, 100],
       [  3, 100,   9]])

In [231]:
arr[:-1,:]

array([[100, 100, 100]])

In [232]:
arr[:-1,:-1]

array([[100, 100]])

### Shape Manipulation

In [233]:
print(arr)
print(arr.shape)
arr = arr.reshape(2,3)
print(arr)

[[100 100 100]
 [  3 100   9]]
(2, 3)
[[100 100 100]
 [  3 100   9]]


In [234]:
arr.ravel(order='C')

array([100, 100, 100,   3, 100,   9])

In [235]:
arr.ravel(order = 'F')

array([100,   3, 100, 100, 100,   9])

In [236]:
arr.flat

In [237]:
list(arr.flat)

[100, 100, 100, 3, 100, 9]

In [238]:
np.array(arr.flat)

array([100, 100, 100,   3, 100,   9])

In [239]:
print(arr1)

[[[1 2 1]
  [4 5 3]
  [7 8 9]]]


In [240]:
arr1.ravel()

array([1, 2, 1, 4, 5, 3, 7, 8, 9])

In [241]:
list(arr1.flat)

[1, 2, 1, 4, 5, 3, 7, 8, 9]

In [242]:
np.array(arr1.flat)

array([1, 2, 1, 4, 5, 3, 7, 8, 9])

### Stacking Together

In [243]:
print(arr)
print(b)

[[100 100 100]
 [  3 100   9]]
[[ 2  4  2]
 [ 6  0 18]]


In [244]:
np.vstack((arr,b))

array([[100, 100, 100],
       [  3, 100,   9],
       [  2,   4,   2],
       [  6,   0,  18]])

In [245]:
np.hstack((arr,b))

array([[100, 100, 100,   2,   4,   2],
       [  3, 100,   9,   6,   0,  18]])

In [246]:
col = np.arange(2)
col

array([0, 1])

In [7]:
temp1 = np.array((1, 2, 3))
temp2 = np.array((10, 20, 39))
np.column_stack((temp1, temp2))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 39]])

In [247]:
np.column_stack((arr, col))

array([[100, 100, 100,   0],
       [  3, 100,   9,   1]])

In [248]:
np.hstack((arr, col.reshape(2,1)))

array([[100, 100, 100,   0],
       [  3, 100,   9,   1]])

In [249]:
np.tile(arr,(3,1))

array([[100, 100, 100],
       [  3, 100,   9],
       [100, 100, 100],
       [  3, 100,   9],
       [100, 100, 100],
       [  3, 100,   9]])

In [250]:
np.tile(arr,(3,2))

array([[100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9],
       [100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9],
       [100, 100, 100, 100, 100, 100],
       [  3, 100,   9,   3, 100,   9]])

### Splitting Array

In [251]:
print(arr)
np.hsplit(arr,3)

[[100 100 100]
 [  3 100   9]]


[array([[100],
        [  3]]), array([[100],
        [100]]), array([[100],
        [  9]])]

In [252]:
np.vsplit(arr,2)

[array([[100, 100, 100]]), array([[  3, 100,   9]])]

### Copies and views

In [253]:
c = arr
c is arr

True

In [254]:
arr

array([[100, 100, 100],
       [  3, 100,   9]])

In [255]:
d = arr[:1,:]
d

array([[100, 100, 100]])

In [256]:
d is arr

False

In [257]:
d.base is arr

False

In [258]:
d[0,0] = 112
print(d)
print(arr)

[[112 100 100]]
[[112 100 100]
 [  3 100   9]]


In [259]:
# Function calls make no copy
def func(x):
    print(id(x))
func(arr)
print(id(arr))

139930305076640
139930305076640


In [260]:
def func1(x):
    print("x= ",x)
    print("xId= ",id(x))
    x[0,0]= 197
    temp = np.ones((3,2))
    print("tempId= ",id(temp))
    x = temp
    x[0,0]=36
    print("x= ",x)
    print("xId= ",id(x))

print(arr)
print(id(arr))
func1(arr)
print(arr)
print(id(arr))

[[112 100 100]
 [  3 100   9]]
139930305076640
x=  [[112 100 100]
 [  3 100   9]]
xId=  139930305076640
tempId=  139930303873392
x=  [[ 36.   1.]
 [  1.   1.]
 [  1.   1.]]
xId=  139930303873392
[[197 100 100]
 [  3 100   9]]
139930305076640


### Indexing more    

In [261]:
print(arr)

[[197 100 100]
 [  3 100   9]]


In [262]:
ind = np.array([0,1])
arr[ind, 0:3]

array([[197, 100, 100],
       [  3, 100,   9]])